# Generated by Django 4.1.7 on 2023-04-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0003_student_courses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name')},
        ),
    ]
