# Generated by Django 4.1.7 on 2023-04-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_alter_student_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Date of event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Finish time', verbose_name='Finish time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar.student')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
                'db_table': 'events',
            },
        ),
    ]
