# Generated by Django 4.1.7 on 2023-04-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0005_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
