# Generated by Django 4.1.7 on 2023-04-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0006_rename_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='course',
        ),
        migrations.RemoveField(
            model_name='event',
            name='student',
        ),
    ]
