# Generated by Django 4.1.7 on 2023-04-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_remove_event_course_remove_event_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
