# Generated by Django 4.1.7 on 2023-04-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0008_remove_student_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
