# Generated by Django 4.1.7 on 2023-04-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0010_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
