# Generated by Django 4.1.7 on 2023-04-03 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(help_text='Last name', max_length=100, verbose_name='last_name')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('courses', models.ManyToManyField(to='course.course')),
            ],
            options={
                'db_table': 'students',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
